version: '3.4'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 3308:3306
    networks:
      - wordpress-network
    env_file:
      - ./db.env
  wordpress:
    image: wordpress:latest
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html
    environment:
      TZ: America/Sao_Paulo
    env_file:
      - ./wp.env
    ports:
      - 8000:80
    networks:
      - wordpress-network
networks:
    wordpress-network:
      driver: bridge